In [2]:
import time
import pandas as pd
from selenium import webdriver 
from selenium.webdriver.common.action_chains import ActionChains 
from selenium.webdriver.common.by import By
from bs4 import *
import requests

1. Write a python program which searches all the product under a particular product vertical
from www.amazon.in. The product verticals to be searched will be taken as input from user.
For e.g. If user input is ‘guitar’. Then search for guitars.

In [47]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get("https://www.amazon.in/")

In [19]:
search = driver.find_element_by_id("twotabsearchtextbox")
search.send_keys(input())

shoes

In [20]:
search_btn=driver.find_element_by_id("nav-search-submit-button")
search_btn.click()

2. In the above question, now scrape the following details of each product listed in first 3 pages
of your search results and save it in a data frame and csv. In case if any product vertical has
less than 3 pages in search results then scrape all the products available under that product
vertical. Details to be scraped are: "Brand Name", "Name of the Product", "Rating", "No. of
Ratings", "Price", "Return/Exchange", "Expected Delivery", "Availability", "Other Details"
and “Product URL”. In case, if any of the details are missing for any of the product then
replace it by “-“.

In [21]:
data = []    
page_count = 1
columns = ["Brand Name","Name of the Product","Price"]

for i in range(3):
    time.sleep(3)
    products = driver.find_elements(By.XPATH,"//div[@class='a-section a-spacing-medium a-text-center']//div[@class='a-section a-spacing-none']")
    print(f"Products in page {page_count}: ",len(products))
    
    for product in products:
        
        try:
            b_name=product.find_element(By.XPATH,".//h5[@class='s-line-clamp-1']/span").text
            data_row = product.text.split("\n")
        except:
            b_name="-"
        try:
            name=product.find_element(By.XPATH,".//span[@class='a-size-base-plus a-color-base a-text-normal']").text
        except:
            name="-"
        try:
            price=product.find_element(By.XPATH,".//span[@class='a-price-whole']").text
        except:
            price="-"
                    
        data.append([b_name,name,price])
        
    page_count += 1
    driver.find_element_by_xpath("//li[@class='a-last']").click()
    time.sleep(2)
print("Done Scraping!!!")

Products in page 1:  76
Products in page 2:  60
Products in page 3:  60
Done Scraping!!!

In [22]:
df=pd.DataFrame(data,columns=columns)
df

,Brand Name,Name of the Product,Price
0,ASIAN,"Men's Bouncer-01 Sports,Walking,Gym,Training,R...",719
1,ASIAN,"Men's Rider-01 Phylon Sports,Running,Walking S...","1,399"
2,ASIAN,"Men's Cosko Running,Walking,Gym,Training Shoes",599
3,ASIAN,"Men's Worldcup-03 Running,Sports,Gym,Phylon Sp...","1,169"
4,CLYMB,Outdoor Sports Running Shoes for Mens Boy,357
...,...,...,...
191,Lancer,Men Dragon Running Shoes,809
192,FURO by Redchief,Men's H20004 F005 Footwear,"1,825"
193,Adidas,Men's Response Sr Running Shoe,"5,319"
194,ASIAN,"Wonder-11 Running Shoes,Training Shoes,Gym Sho...",539
195,Adidas,Unisex-Adult Response Super 2.0 J Running Shoe,"4,733"

In [24]:
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[1]/div[1]/div/span[3]/div[2]/div[64]/span/div/div/ul/li[2]/a").click()

In [25]:
page_url = [] 
for i in range(3):
    url = driver.find_elements_by_xpath("//a[@class='a-link-normal a-text-normal']")
    for j in url:
        page_url.append(j.get_attribute('href'))
    driver.find_element_by_xpath("//li[@class='a-last']").click()
    time.sleep(2)

In [26]:
len(page_url)

211

In [150]:
rating=[]
n_rating=[]
av=[]
r=[]
e=[]
for i in page_url: 
        driver.get(i)
        time.sleep(3)
        try:
            ratings = driver.find_element_by_xpath("//span[@class='a-size-base a-nowrap']")
            rating.append(ratings.text)
        except:
            ratings=driver.find_element_by_xpath("//h3[@class='a-spacing-small']")
            rating.append(ratings.text)
        
        try:
            n_ratings = driver.find_element_by_xpath("//span[@id='acrCustomerReviewText']")
            n_rating.append(n_ratings.text)
        except:
            n_ratings="-"
            n_rating.append(n_ratings)
        
        try:
            avs= driver.find_element_by_xpath("//div[@id='availability']")
            av.append(avs.text)
        except:
            avs="-"
            av.append(avs)
        
        try:
            es= driver.find_element_by_xpath("//div[@id='ddmDeliveryMessage']")
            e.append(es.text)
        except:
            es="-"
            e.append(es)

In [157]:
df["product URL"]=page_url
df["ratings"]=rating
df["No.of.ratings"]=n_rating
df["availability"]=av
df["expected delivery"]=e

In [158]:
df

,Brand Name,Name of the Product,Price,product URL,ratings,No.of.ratings,availability,expected delivery
0,Bourge,Vega Pearl-z2,683,https://www.amazon.in/gp/slredirect/picassoRed...,4.2 out of 5,"45,101 ratings",In stock.,"FREE delivery: Saturday, Oct 23 Details\nFaste..."
1,Generic,Fashion Sport,-,https://www.amazon.in/gp/slredirect/picassoRed...,No customer reviews,-,,-
2,Big Fox,Bfs_538,719,https://www.amazon.in/gp/slredirect/picassoRed...,4.3 out of 5,3 ratings,In stock.,"FREE delivery: Wednesday, Oct 27 Details"
3,Generic,Jaden Freeman Men's Mesh Sports Running Shoes,-,https://www.amazon.in/gp/slredirect/picassoRed...,2.3 out of 5,17 ratings,,-
4,CLYMB,Pilot,357,https://www.amazon.in/CLYMB-Mens-Black-Running...,2.9 out of 5,"3,622 ratings",-,
...,...,...,...,...,...,...,...,...
189,DSC,Men's Beamer Cricket Shoes,575,https://www.amazon.in/Amazon-Brand-Symactive-R...,4 out of 5,258 ratings,-,
190,Centrino,Sports shoe for Mens,609,https://www.amazon.in/gp/slredirect/picassoRed...,4 out of 5,192 ratings,In stock.,"FREE delivery: Tuesday, Oct 26 Details"
191,Klepe,Men's Running Shoes,549,https://www.amazon.in/gp/slredirect/picassoRed...,5 out of 5,2 ratings,Only 5 left in stock.,"FREE delivery: Wednesday, Oct 27 Details"
192,Klepe,Y10,399,https://www.amazon.in/gp/slredirect/picassoRed...,3.6 out of 5,24 ratings,In stock.,"FREE delivery: Saturday, Oct 23 Details\nFaste..."
193,Klepe,Men's Running Shoes,599,https://www.amazon.in/gp/slredirect/picassoRed...,3.4 out of 5,96 ratings,In stock.,"FREE delivery: Sunday, Oct 24 Details\nFastest..."

In [17]:
df.to_csv("amazon product details.csv", index=False)

In [27]:
driver.close()

3. Write a python program to access the search bar and search button on images.google.com and
scrape 100 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’

In [30]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get("https://images.google.com/")

In [84]:
imgs=[]
keywords=["fruits","cars","Machine Learning"]
counter=1
while(counter<100):
    for i in keywords:
        search = driver.find_element_by_xpath("//input[@class='gLFyf gsfi']")
        search.send_keys(i)
        search_btn=driver.find_element_by_xpath("//button[@class='Tg7LZd']")
        search_btn.click()
        time.sleep(2)
        img=driver.find_elements_by_xpath("//img[@class='rg_i Q4LuWd']")
        for j in img:
            imgs.append(j.get_attribute('src'))
            if(counter>100):
                    break
            else:
                counter+=1
        
        driver.get("https://images.google.com/")
        time.sleep(2)
    print("done")
    break

done

In [85]:
df=pd.DataFrame(imgs,columns=["Images"])
df

                                                Images
0    data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
1    data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
2    data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
3    data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
4    data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
..                                                 ...
96   data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
97   data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
98   data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
99   data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
100  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...

[101 rows x 1 columns]

In [89]:
df.to_csv("google images.csv", index=False)

In [90]:
driver.close()

4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on
www.flipkart.com and scrape following details for all the search results displayed on 1st page.
Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”,
“Storage(ROM)”, “Primary Camera”, “Secondary Camera”, “Display Size”, “Display
Resolution”, “Processor”, “Processor Cores”, “Battery Capacity”, “Price”, “Product URL”.
Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe
and CSV

In [119]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get("https://www.flipkart.com/")

In [120]:
login_pop=driver.find_element_by_xpath("//button[@class='_2KpZ6l _2doB4z']")
login_pop.click()
search_job = driver.find_element_by_xpath("//input[@placeholder='Search for products, brands and more']")
search_job.send_keys(input())

pixel 4a

In [121]:
search_btn=driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_btn.click()

In [122]:
data = []    
columns = ["product name","Price","other specifications","product url"]
products = driver.find_elements(By.XPATH,"//div[@class='_1AtVbE col-12-12']//div[@class='_2kHMtA']")
for product in products:
   
    try:
        name=product.find_element(By.XPATH,".//div[@class='_4rR01T']").text
    except:
        name="-"
    try:
        price=product.find_element(By.XPATH,".//div[@class='_30jeq3 _1_WHN1']").text
    except:
        price="-"
    try:
        other_details=product.find_element(By.XPATH,".//div[@class='fMghEO']").text
    except:
        other_details="-"
    url=product.find_element(By.XPATH,".//a[@class='_1fQZEK']").get_attribute('href')
    data.append([name,price,other_details,url])

In [123]:
data

[['Google Pixel 4a (Just Black, 128 GB)',
  '₹25,999',
  '6 GB RAM | 128 GB ROM\n14.76 cm (5.81 inch) Full HD+ Display\n12.2MP Rear Camera | 8MP Front Camera\n3140 mAh Battery\nQualcomm Snapdragon 730G Processor\nOLED Display\n1 Year Warranty',
  'https://www.flipkart.com/google-pixel-4a-just-black-128-gb/p/itm023b9677aa45d?pid=MOBFUSBNAZGY7HQU&lid=LSTMOBFUSBNAZGY7HQUWHTF0C&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_1&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBFUSBNAZGY7HQU.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['REDMI 9 Power (Fiery Red, 64 GB)',
  '₹11,499',
  '4 GB RAM | 64 GB ROM\n16.59 cm (6.53 inch) Full HD+ Display\n48MP + 8MP + 2MP + 2MP | 8MP Front Camera\n6000 mAh Battery\nQualcomm Snapdragon 662 Processor\n1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase',
  'https://www.flipkart.com/redmi-9-power-fiery-red-64-gb/p/itmcd78b9bc04aa9?pid=MOBFYZF8XVSHPK5M&lid=LSTMOBFYZF8XVSHPK5MLN0BYU&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_2&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBFYZF8XVSHPK5M.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['REDMI 9 Power (Electric Green, 64 GB)',
  '₹11,499',
  '4 GB RAM | 64 GB ROM\n16.59 cm (6.53 inch) Full HD+ Display\n48MP + 8MP + 2MP + 2MP | 8MP Front Camera\n6000 mAh Battery\nQualcomm Snapdragon 662 Processor\n1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase',
  'https://www.flipkart.com/redmi-9-power-electric-green-64-gb/p/itmca7d78e222ed7?pid=MOBFYZ7AVAXXB2TH&lid=LSTMOBFYZ7AVAXXB2THSURAUV&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_3&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBFYZ7AVAXXB2TH.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['REDMI 9 Power (Mighty Black, 64 GB)',
  '₹11,499',
  '4 GB RAM | 64 GB ROM\n16.59 cm (6.53 inch) Full HD+ Display\n48MP + 8MP + 2MP + 2MP | 8MP Front Camera\n6000 mAh Battery\nQualcomm Snapdragon 662 Processor\n1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase',
  'https://www.flipkart.com/redmi-9-power-mighty-black-64-gb/p/itm481ab234a6553?pid=MOBFYZ94UWPWQRNF&lid=LSTMOBFYZ94UWPWQRNFD8SF5T&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_4&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBFYZ94UWPWQRNF.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['REDMI 9 Power (Blazing Blue, 64 GB)',
  '₹11,499',
  '4 GB RAM | 64 GB ROM\n16.59 cm (6.53 inch) Full HD+ Display\n48MP + 8MP + 2MP + 2MP | 8MP Front Camera\n6000 mAh Battery\nQualcomm Snapdragon 662 Processor\n1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase',
  'https://www.flipkart.com/redmi-9-power-blazing-blue-64-gb/p/itm9533b02ba34ef?pid=MOBFYZ7HHGJUATYD&lid=LSTMOBFYZ7HHGJUATYDW4Q2OX&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_5&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBFYZ7HHGJUATYD.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['I Kall Z5 (Green, 16 GB)',
  '₹4,995',
  '3 GB RAM | 16 GB ROM\n13.84 cm (5.45 inch) Display\n8MP Rear Camera | 5MP Front Camera\n3000 mAh Battery\n1 year manufacturing warranty for mobile and 6 months for box accessories',
  'https://www.flipkart.com/kall-z5-green-16-gb/p/itmd861401a8b939?pid=MOBG7FGHHHHZFHZ9&lid=LSTMOBG7FGHHHHZFHZ9BQANIH&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_6&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBG7FGHHHHZFHZ9.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['REDMI 10 Prime (Phantom Black, 64 GB)',
  '₹13,936',
  '4 GB RAM | 64 GB ROM | Expandable Upto 512 GB\n16.51 cm (6.5 inch) Full HD Display\n50MP + 8MP + 2MP + 2MP | 8MP Front Camera\n6000 mAh Battery\nHelio G88 Processor\n1 Year Manufacturer Warranty for Handset and 6 Months Warranty for In the Box Accessories',
  'https://www.flipkart.com/redmi-10-prime-phantom-black-64-gb/p/itm9377b4c936baa?pid=MOBG6RGHHA2DGZZY&lid=LSTMOBG6RGHHA2DGZZY9ECJXA&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_7&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBG6RGHHA2DGZZY.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['Redmi 9 (Sporty Orange, 64 GB)',
  '₹9,308',
  '4 GB RAM | 64 GB ROM\n16.59 cm (6.53 inch) HD+ Display\n13MP + 2MP | 5MP Front Camera\n5000 mAh Battery\nMediaTek Helio G35 Processor\n1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase',
  'https://www.flipkart.com/redmi-9-sporty-orange-64-gb/p/itm4fb151383983b?pid=MOBFV5FPCJC9ZKRB&lid=LSTMOBFV5FPCJC9ZKRBPHFKQZ&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_8&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBFV5FPCJC9ZKRB.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['OPPO A16 (Crystal Black, 64 GB)',
  '₹12,857',
  '4 GB RAM | 64 GB ROM\n16.56 cm (6.52 inch) Display\n13MP Rear Camera\n5000 mAh Battery\nBrand Warranty of 1 Year Available for Mobile Including Battery and 6 Months for Accessories',
  'https://www.flipkart.com/oppo-a16-crystal-black-64-gb/p/itmeeb6ad985655f?pid=MOBG7FKZKUR7MNYZ&lid=LSTMOBG7FKZKUR7MNYZ3WDEZA&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_9&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBG7FKZKUR7MNYZ.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['OPPO A16 (Pearl Blue, 64 GB)',
  '₹13,320',
  '4 GB RAM | 64 GB ROM\n16.56 cm (6.52 inch) Display\n13MP Rear Camera\n5000 mAh Battery\nBrand Warranty of 1 Year Available for Mobile Including Battery and 6 Months for Accessories',
  'https://www.flipkart.com/oppo-a16-pearl-blue-64-gb/p/itmeeb6ad985655f?pid=MOBG7FNH8GMZGMYT&lid=LSTMOBG7FNH8GMZGMYTZEY3R7&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_10&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBG7FNH8GMZGMYT.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['Redmi 9 (Carbon Black, 64 GB)',
  '₹9,295',
  '4 GB RAM | 64 GB ROM\n16.59 cm (6.53 inch) HD+ Display\n13MP + 2MP | 5MP Front Camera\n5000 mAh Battery\nMediaTek Helio G35 Processor\n1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase',
  'https://www.flipkart.com/redmi-9-carbon-black-64-gb/p/itm4fb151383983b?pid=MOBFVHMPGATFZXWR&lid=LSTMOBFVHMPGATFZXWRBPPMMR&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_11&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBFVHMPGATFZXWR.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['Redmi 9 (Sky Blue, 64 GB)',
  '₹9,374',
  '4 GB RAM | 64 GB ROM\n16.59 cm (6.53 inch) HD+ Display\n13MP + 2MP | 5MP Front Camera\n5000 mAh Battery\nMediaTek Helio G35 Processor\n1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase',
  'https://www.flipkart.com/redmi-9-sky-blue-64-gb/p/itm4fb151383983b?pid=MOBFV5FPUS8UHG9H&lid=LSTMOBFV5FPUS8UHG9H8HEZGA&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_12&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBFV5FPUS8UHG9H.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['Tecno Spark 7T (Nebula Orange, 128 GB)',
  '₹10,990',
  '4 GB RAM | 128 GB ROM | Expandable Upto 256 GB\n16.56 cm (6.52 inch) HD+ Display\n48MP Rear Camera | 8MP Front Camera\n6000 mAh Battery\nHelio G35 Processor\nOne Year Warranty for Handset, 6 Months for Accessories',
  'https://www.flipkart.com/tecno-spark-7t-nebula-orange-128-gb/p/itmd78a578fca8d6?pid=MOBG7F6RUGHFTDPS&lid=LSTMOBG7F6RUGHFTDPS6FMXMN&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_13&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBG7F6RUGHFTDPS.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['SAMSUNG Galaxy M02 (Gray, 32 GB)',
  '₹8,470',
  '3 GB RAM | 32 GB ROM\n16.64 cm (6.55 inch) Full HD+ Display\n13MP + 2MP | 5MP Front Camera\n5000 mAh Battery\nMediaTek MT6739 Processor\n1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase',
  'https://www.flipkart.com/samsung-galaxy-m02-gray-32-gb/p/itm9f00523932d79?pid=MOBGY73CF6SYPZ3S&lid=LSTMOBGY73CF6SYPZ3SPY2WNT&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_14&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBGY73CF6SYPZ3S.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['REDMI 9 Power (Mighty Black, 128 GB)',
  '₹15,924',
  '6 GB RAM | 128 GB ROM\n16.59 cm (6.53 inch) Full HD+ Display\n48MP + 8MP + 2MP + 2MP | 8MP Front Camera\n6000 mAh Battery\nQualcomm Snapdragon 662 Processor\n1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase',
  'https://www.flipkart.com/redmi-9-power-mighty-black-128-gb/p/itm74c84b4084cc5?pid=MOBGYMD9AVZZH9WX&lid=LSTMOBGYMD9AVZZH9WXIJAHX4&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_15&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBGYMD9AVZZH9WX.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['REDMI 9 Power (Blazing Blue, 128 GB)',
  '₹15,979',
  '6 GB RAM | 128 GB ROM\n16.59 cm (6.53 inch) Full HD+ Display\n48MP + 8MP + 2MP + 2MP | 8MP Front Camera\n6000 mAh Battery\nQualcomm Snapdragon 662 Processor\n1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase',
  'https://www.flipkart.com/redmi-9-power-blazing-blue-128-gb/p/itm3e12ae178efdf?pid=MOBGYMD86ZWAA6GS&lid=LSTMOBGYMD86ZWAA6GSW7ZC9R&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_16&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBGYMD86ZWAA6GS.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['SAMSUNG Galaxy M31 (Space Black, 64 GB)',
  '₹15,999',
  '6 GB RAM | 64 GB ROM | Expandable Upto 512 GB\n16.26 cm (6.4 inch) Full HD+ Display\n64MP + 8MP + 5MP + 5MP | 32MP Front Camera\n6000 mAh Battery\nSamsung Exynos 9 Octa 9611 Processor\n1 year',
  'https://www.flipkart.com/samsung-galaxy-m31-space-black-64-gb/p/itme0c5a25c1e64a?pid=MOBFPNPSZWQ7YKGH&lid=LSTMOBFPNPSZWQ7YKGHGQDQLJ&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_17&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBFPNPSZWQ7YKGH.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['Panasonic ELUGA I6 (Black, 16 GB)',
  '₹5,490',
  '2 GB RAM | 16 GB ROM | Expandable Upto 256 GB\n13.84 cm (5.45 inch) FWVGA Display\n8MP Rear Camera | 5MP Front Camera\n3000 mAh Battery\nMediaTek Processor\nBrand Warranty of 1 Year Available for Mobile and 6 Months for Accessories',
  'https://www.flipkart.com/panasonic-eluga-i6-black-16-gb/p/itm876e1eeb85ac1?pid=MOBFS3GJ5CR7PVEW&lid=LSTMOBFS3GJ5CR7PVEWNORSVR&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_18&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBFS3GJ5CR7PVEW.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['Redmi 9A (SeaBlue, 32 GB)',
  '₹7,989',
  '2 GB RAM | 32 GB ROM\n16.59 cm (6.53 inch) Full HD+ Display\n13MP Rear Camera\n5000 mAh Battery\n1 Year Manufacturer Warranty',
  'https://www.flipkart.com/redmi-9a-seablue-32-gb/p/itmeabd39a0cd669?pid=MOBFVD9ZGTYR2WGR&lid=LSTMOBFVD9ZGTYR2WGRRTPFAV&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_19&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBFVD9ZGTYR2WGR.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['Tecno Spark 7 (Magnet Black, 32 GB)',
  '₹7,813',
  '2 GB RAM | 32 GB ROM | Expandable Upto 256 GB\n16.56 cm (6.52 inch) HD+ Display\n16MP Rear Camera | 8MP Front Camera\n6000 mAh Battery\nHelio A25 Processor\nOne Year Warranty for Handset, 6 Months for Accessories',
  'https://www.flipkart.com/tecno-spark-7-magnet-black-32-gb/p/itmb5ba6405b2fec?pid=MOBG6FN2JPZXMAYU&lid=LSTMOBG6FN2JPZXMAYUIF9BJT&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_20&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBG6FN2JPZXMAYU.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['Itel it5026',
  '₹1,099',
  '4 MB RAM | 4 MB ROM\n6.1 cm (2.4 inch) Display\n2MP Rear Camera\n1200 mAh Battery\n1 Year Manufacturer Warranty on handset and six month of accessories',
  'https://www.flipkart.com/itel-it5026/p/itm2d630b978656b?pid=MOBFXMP7GSETA7RX&lid=LSTMOBFXMP7GSETA7RXEFRNOE&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_21&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBFXMP7GSETA7RX.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['SAMSUNG Galaxy M02 (Black, 32 GB)',
  '₹8,262',
  '2 GB RAM | 32 GB ROM\n16.64 cm (6.55 inch) Full HD+ Display\n13MP + 2MP | 5MP Front Camera\n5000 mAh Battery\nMediaTek MT6739 Processor\n1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase',
  'https://www.flipkart.com/samsung-galaxy-m02-black-32-gb/p/itm16e9cd93db916?pid=MOBGY73CSBKNXA5W&lid=LSTMOBGY73CSBKNXA5WNQLDVS&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_22&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBGY73CSBKNXA5W.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['OPPO A55 (Starry Black, 64 GB)',
  '₹15,480',
  '4 GB RAM | 64 GB ROM\n16.54 cm (6.51 inch) Display\n50MP Rear Camera\n5000 mAh Battery\nBrand Warranty of 1 Year Available for Mobile Including Battery and 6 Months for Accessories',
  'https://www.flipkart.com/oppo-a55-starry-black-64-gb/p/itmfd07b94a9a543?pid=MOBG7FMJGBPWKCQT&lid=LSTMOBG7FMJGBPWKCQTSLN8OB&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_23&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBG7FMJGBPWKCQT.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032'],
 ['OPPO A55 (Rainbow Blue, 64 GB)',
  '₹15,480',
  '4 GB RAM | 64 GB ROM\n16.54 cm (6.51 inch) Display\n50MP Rear Camera\n5000 mAh Battery\nBrand Warranty of 1 Year Available for Mobile Including Battery and 6 Months for Accessories',
  'https://www.flipkart.com/oppo-a55-rainbow-blue-64-gb/p/itmfd07b94a9a543?pid=MOBG7FMQYH2HAM64&lid=LSTMOBG7FMQYH2HAM64NINTAC&marketplace=FLIPKART&q=pixel+4a&store=tyy%2F4io&srno=s_1_24&otracker=search&otracker1=search&fm=SEARCH&iid=aaea36a7-c3d8-4ffc-b757-0c605047a8d0.MOBG7FMQYH2HAM64.SEARCH&ppt=hp&ppn=homepage&ssid=565osugjn40000001634889196195&qH=614b192c242ae032']]

In [124]:
df=pd.DataFrame(data,columns=columns)
df

,product name,Price,other specifications,product url
0,"Google Pixel 4a (Just Black, 128 GB)","₹25,999",6 GB RAM | 128 GB ROM\n14.76 cm (5.81 inch) Fu...,https://www.flipkart.com/google-pixel-4a-just-...
1,"REDMI 9 Power (Fiery Red, 64 GB)","₹11,499",4 GB RAM | 64 GB ROM\n16.59 cm (6.53 inch) Ful...,https://www.flipkart.com/redmi-9-power-fiery-r...
2,"REDMI 9 Power (Electric Green, 64 GB)","₹11,499",4 GB RAM | 64 GB ROM\n16.59 cm (6.53 inch) Ful...,https://www.flipkart.com/redmi-9-power-electri...
3,"REDMI 9 Power (Mighty Black, 64 GB)","₹11,499",4 GB RAM | 64 GB ROM\n16.59 cm (6.53 inch) Ful...,https://www.flipkart.com/redmi-9-power-mighty-...
4,"REDMI 9 Power (Blazing Blue, 64 GB)","₹11,499",4 GB RAM | 64 GB ROM\n16.59 cm (6.53 inch) Ful...,https://www.flipkart.com/redmi-9-power-blazing...
5,"I Kall Z5 (Green, 16 GB)","₹4,995",3 GB RAM | 16 GB ROM\n13.84 cm (5.45 inch) Dis...,https://www.flipkart.com/kall-z5-green-16-gb/p...
6,"REDMI 10 Prime (Phantom Black, 64 GB)","₹13,936",4 GB RAM | 64 GB ROM | Expandable Upto 512 GB\...,https://www.flipkart.com/redmi-10-prime-phanto...
7,"Redmi 9 (Sporty Orange, 64 GB)","₹9,308",4 GB RAM | 64 GB ROM\n16.59 cm (6.53 inch) HD+...,https://www.flipkart.com/redmi-9-sporty-orange...
8,"OPPO A16 (Crystal Black, 64 GB)","₹12,857",4 GB RAM | 64 GB ROM\n16.56 cm (6.52 inch) Dis...,https://www.flipkart.com/oppo-a16-crystal-blac...
9,"OPPO A16 (Pearl Blue, 64 GB)","₹13,320",4 GB RAM | 64 GB ROM\n16.56 cm (6.52 inch) Dis...,https://www.flipkart.com/oppo-a16-pearl-blue-6...
10,"Redmi 9 (Carbon Black, 64 GB)","₹9,295",4 GB RAM | 64 GB ROM\n16.59 cm (6.53 inch) HD+...,https://www.flipkart.com/redmi-9-carbon-black-...
11,"Redmi 9 (Sky Blue, 64 GB)","₹9,374",4 GB RAM | 64 GB ROM\n16.59 cm (6.53 inch) HD+...,https://www.flipkart.com/redmi-9-sky-blue-64-g...
12,"Tecno Spark 7T (Nebula Orange, 128 GB)","₹10,990",4 GB RAM | 128 GB ROM | Expandable Upto 256 GB...,https://www.flipkart.com/tecno-spark-7t-nebula...
13,"SAMSUNG Galaxy M02 (Gray, 32 GB)","₹8,470",3 GB RAM | 32 GB ROM\n16.64 cm (6.55 inch) Ful...,https://www.flipkart.com/samsung-galaxy-m02-gr...
14,"REDMI 9 Power (Mighty Black, 128 GB)","₹15,924",6 GB RAM | 128 GB ROM\n16.59 cm (6.53 inch) Fu...,https://www.flipkart.com/redmi-9-power-mighty-...
15,"REDMI 9 Power (Blazing Blue, 128 GB)","₹15,979",6 GB RAM | 128 GB ROM\n16.59 cm (6.53 inch) Fu...,https://www.flipkart.com/redmi-9-power-blazing...
16,"SAMSUNG Galaxy M31 (Space Black, 64 GB)","₹15,999",6 GB RAM | 64 GB ROM | Expandable Upto 512 GB\...,https://www.flipkart.com/samsung-galaxy-m31-sp...
17,"Panasonic ELUGA I6 (Black, 16 GB)","₹5,490",2 GB RAM | 16 GB ROM | Expandable Upto 256 GB\...,https://www.flipkart.com/panasonic-eluga-i6-bl...
18,"Redmi 9A (SeaBlue, 32 GB)","₹7,989",2 GB RAM | 32 GB ROM\n16.59 cm (6.53 inch) Ful...,https://www.flipkart.com/redmi-9a-seablue-32-g...
19,"Tecno Spark 7 (Magnet Black, 32 GB)","₹7,813",2 GB RAM | 32 GB ROM | Expandable Upto 256 GB\...,https://www.flipkart.com/tecno-spark-7-magnet-...
20,Itel it5026,"₹1,099",4 MB RAM | 4 MB ROM\n6.1 cm (2.4 inch) Display...,https://www.flipkart.com/itel-it5026/p/itm2d63...
21,"SAMSUNG Galaxy M02 (Black, 32 GB)","₹8,262",2 GB RAM | 32 GB ROM\n16.64 cm (6.55 inch) Ful...,https://www.flipkart.com/samsung-galaxy-m02-bl...
22,"OPPO A55 (Starry Black, 64 GB)","₹15,480",4 GB RAM | 64 GB ROM\n16.54 cm (6.51 inch) Dis...,https://www.flipkart.com/oppo-a55-starry-black...
23,"OPPO A55 (Rainbow Blue, 64 GB)","₹15,480",4 GB RAM | 64 GB ROM\n16.54 cm (6.51 inch) Dis...,https://www.flipkart.com/oppo-a55-rainbow-blue...

In [125]:
driver.close()

5. Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on
google maps.

In [13]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get("https://www.google.com/maps")

In [14]:
search = driver.find_element_by_id("searchboxinput")
search.send_keys(input())

gujarat

In [15]:
search_btn=driver.find_element_by_xpath("//div[@class='xoLGzf-BIqFsb-haAclf']")
search_btn.click()

In [16]:
url_string = driver.current_url.replace("@","")
split=url_string.split(",")
split

['https://www.google.com/maps/search/gujarat/13.0383872', '80.2062336', '12z']

In [17]:
len(split)

3

In [18]:
if(len(split)==4):
    latitude=split[1].replace('+','')
    longitude=split[2]
    print("LATITUDE=",latitude,"\n","LONGITUDE=",longitude)
elif(len(split)==3):
    latitude=split[0].replace('/',' ')
    longitude=split[1]
    print("LATITUDE=",latitude,"\n","LONGITUDE=",longitude)  
else:
    latitude=split[2].replace('+','')
    longitude=split[3]
    print("LATITUDE=",latitude,"\n","LONGITUDE=",longitude)

LATITUDE= https:  www.google.com maps search gujarat 13.0383872
 LONGITUDE= 80.2062336

In [12]:
driver.close()

6. Write a program to scrap details of all the funding deals for second quarter (i.e. July 20 –
September 20) from trak.in

In [92]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get("https://trak.in/")

In [93]:
url=driver.find_element_by_xpath("//a[@title='http://trak.in/india-startup-funding-investment-2015/']")

In [94]:
funding_link=url.get_attribute('href')
driver.get(funding_link)

JULY 2020 SCRAP

In [95]:
date=[]
startup=[]
vertical=[]
sub_vertical=[]
city=[]
investor_name=[]
investor_type=[]
amount=[]

date_tag = driver.find_elements_by_xpath('//table[@id="tablepress-48"]/tbody/tr/td[2]')
for i in date_tag:
    date.append(i.text)

st = driver.find_elements_by_xpath('//table[@id="tablepress-48"]/tbody/tr/td[3]')
for i in st:
    startup.append(i.text)
    
v= driver.find_elements_by_xpath('//table[@id="tablepress-48"]/tbody/tr/td[4]')
for i in v:
    vertical.append(i.text)
    
sv = driver.find_elements_by_xpath('//table[@id="tablepress-48"]/tbody/tr/td[5]')
for i in sv:
    sub_vertical.append(i.text)
    
c = driver.find_elements_by_xpath('//table[@id="tablepress-48"]/tbody/tr/td[6]')
for i in c:
    city.append(i.text)
    
In = driver.find_elements_by_xpath('//table[@id="tablepress-48"]/tbody/tr/td[7]')
for i in In:
    investor_name.append(i.text)
    
it= driver.find_elements_by_xpath('//table[@id="tablepress-48"]/tbody/tr/td[8]')
for i in it:
    investor_type.append(i.text)
    
a = driver.find_elements_by_xpath('//table[@id="tablepress-48"]/tbody/tr/td[9]')
for i in a:
    amount.append(i.text)

In [96]:
df1=pd.DataFrame()
df1["DATE"]=date
df1["STARTUP"]=startup
df1["VERTICAL"]=vertical
df1["SUB_VERTICAL"]=sub_vertical
df1["CITY"]=city
df1["INVESTOR_NAME"]=investor_name
df1["INVESTOR_TYPE"]=investor_type
df1["AMOUNT"]=amount
df1

,DATE,STARTUP,VERTICAL,SUB_VERTICAL,CITY,INVESTOR_NAME,INVESTOR_TYPE,AMOUNT
0,15/07/2020,Flipkart,E-commerce,E-commerce,Bangalore,Walmart Inc,M&A,"1,200,000,000"
1,16/07/2020,Vedantu,EduTech,Online Tutoring,Bangalore,Coatue Management,Series D,"100,000,000"
2,16/07/2020,Crio,EduTech,Learning Platform for Developers,Bangalore,021 Capital,pre-Series A,"934,160"
3,14/07/2020,goDutch,FinTech,Group Payments,Mumbai,"Matrix India,Y Combinator, Global Founders Cap...",Seed,"1,700,000"
4,13/07/2020,Mystifly,Airfare Marketplace,"Ticketing, Airline Retailing, and Post-Ticketi...",Singapore and Bangalore,Recruit Co. Ltd.,pre-Series B,"3,300,000"
5,09/07/2020,JetSynthesys,Gaming and Entertainment,Gaming and Entertainment,Pune,Adar Poonawalla and Kris Gopalakrishnan.,Venture-Series Unknown,"400,000"
6,10/07/2020,gigIndia,Marketplace,"Crowd Sourcing, Freelance",Pune,Incubate Fund India and Beyond Next Ventures,pre-Series A,"974,200"
7,15/07/2020,PumPumPum,Automotive Rental,Used Car-leasing platform,Gurgaon,Early Adapters Syndicate,Seed,"292,800"
8,14/07/2020,FLYX,OTT Player,Streaming Social Network,New York and Delhi,"Raj Mishra, founder of AIT Global Inc",pre-Seed,"200,000"
9,13/07/2020,Open Appliances Pvt. Ltd.,Information Technology,Internet-of-Things Security Solutions,Bangalore,Unicorn India Ventures,Venture-Series Unknown,"500,000"

AUGUST 2020 SCRAP

In [97]:
date=[]
startup=[]
vertical=[]
sub_vertical=[]
city=[]
investor_name=[]
investor_type=[]
amount=[]

date_tag = driver.find_elements_by_xpath('//table[@id="tablepress-49"]/tbody/tr/td[2]')
for i in date_tag:
    date.append(i.text)

st = driver.find_elements_by_xpath('//table[@id="tablepress-49"]/tbody/tr/td[3]')
for i in st:
    startup.append(i.text)
    
v= driver.find_elements_by_xpath('//table[@id="tablepress-49"]/tbody/tr/td[4]')
for i in v:
    vertical.append(i.text)
    
sv = driver.find_elements_by_xpath('//table[@id="tablepress-49"]/tbody/tr/td[5]')
for i in sv:
    sub_vertical.append(i.text)
    
c = driver.find_elements_by_xpath('//table[@id="tablepress-49"]/tbody/tr/td[6]')
for i in c:
    city.append(i.text)
    
In = driver.find_elements_by_xpath('//table[@id="tablepress-49"]/tbody/tr/td[7]')
for i in In:
    investor_name.append(i.text)
    
it= driver.find_elements_by_xpath('//table[@id="tablepress-49"]/tbody/tr/td[8]')
for i in it:
    investor_type.append(i.text)
    
a = driver.find_elements_by_xpath('//table[@id="tablepress-49"]/tbody/tr/td[9]')
for i in a:
    amount.append(i.text)

In [98]:
df2=pd.DataFrame()
df2["DATE"]=date
df2["STARTUP"]=startup
df2["VERTICAL"]=vertical
df2["SUB_VERTICAL"]=sub_vertical
df2["CITY"]=city
df2["INVESTOR_NAME"]=investor_name
df2["INVESTOR_TYPE"]=investor_type
df2["AMOUNT"]=amount
df2

,DATE,STARTUP,VERTICAL,SUB_VERTICAL,CITY,INVESTOR_NAME,INVESTOR_TYPE,AMOUNT
0,15/08/2020,Practo,HealthTech,Health care and Wellness,Bangalore,A1A Company,Series F,"32,000,000"
1,13/08/2020,Medlife,E-commerce,Online Pharmacy,Bangalore,Prasid Uno Family Trust and SC Credit Fund,,"23,000,000"
2,13/08/2020,HungerBox,FoodTech,Online Food Delivery Service,Bangalore,"One97, Sabre Partners Trust, Pratithi Investme...",Series D1,"1,560,000"
3,04/08/2020,Dunzo,Hyper-local Logistics,Online Delivery Services,Bangalore,Existing Backers,In Progress,"30,000,000"
4,11/08/2020,Terra.do,EduTech,"Online Climate School, E-learning","Stanford, California,","Stanford Angels and Entrepreneurs (India), BEE...",Seed,"1,400,000"
5,12/08/2020,Classplus,EduTech,"E-learning, Online Tutoring",Noida,Falcon Edge,In Progress,"upto 15,000,000"
6,14/08/2020,Niyo,FinTech,Financial Services,Bangalore,Niyo Solutions Inc.,,"6,000,000"
7,10/08/2020,ZestMoney,FinTech,Financial Services,Bangalore,Primrose Hills Ventures,,"10,670,000"
8,07/08/2020,FreshToHome,E-commerce,Food Delivery,Bangalore,Ascent Capital,Venture,"16,200,000"
9,13/08/2020,Eduvanz,FinTech,Financial Services,Mumbai,"Sequoia India, Unitus",Series A,"5,000,000"

SEPTEMBER 2020 SCRAP

In [99]:
date=[]
startup=[]
vertical=[]
sub_vertical=[]
city=[]
investor_name=[]
investor_type=[]
amount=[]

date_tag = driver.find_elements_by_xpath('//table[@id="tablepress-50"]/tbody/tr/td[2]')
for i in date_tag:
    date.append(i.text)

st = driver.find_elements_by_xpath('//table[@id="tablepress-50"]/tbody/tr/td[3]')
for i in st:
    startup.append(i.text)
    
v= driver.find_elements_by_xpath('//table[@id="tablepress-50"]/tbody/tr/td[4]')
for i in v:
    vertical.append(i.text)
    
sv = driver.find_elements_by_xpath('//table[@id="tablepress-50"]/tbody/tr/td[5]')
for i in sv:
    sub_vertical.append(i.text)
    
c = driver.find_elements_by_xpath('//table[@id="tablepress-50"]/tbody/tr/td[6]')
for i in c:
    city.append(i.text)
    
In = driver.find_elements_by_xpath('//table[@id="tablepress-50"]/tbody/tr/td[7]')
for i in In:
    investor_name.append(i.text)
    
it= driver.find_elements_by_xpath('//table[@id="tablepress-50"]/tbody/tr/td[8]')
for i in it:
    investor_type.append(i.text)
    
a = driver.find_elements_by_xpath('//table[@id="tablepress-50"]/tbody/tr/td[9]')
for i in a:
    amount.append(i.text)

In [100]:
df3=pd.DataFrame()
df3["DATE"]=date
df3["STARTUP"]=startup
df3["VERTICAL"]=vertical
df3["SUB_VERTICAL"]=sub_vertical
df3["CITY"]=city
df3["INVESTOR_NAME"]=investor_name
df3["INVESTOR_TYPE"]=investor_type
df3["AMOUNT"]=amount
df3

,DATE,STARTUP,VERTICAL,SUB_VERTICAL,CITY,INVESTOR_NAME,INVESTOR_TYPE,AMOUNT
0,08/09/2020,Byju’s,EduTech,Online Tutoring,Bangalore,"Silver Lake, Tiger Global, General Atlantic an...",Private Equity,"500,000,000"
1,12/09/2020,mCaffeine,Personal Care,Skincare & Haircare,Mumbai,"Amicus Capital Private Equity I LLP, Amicus Ca...",Series B,"3,000,000"
2,09/09/2020,Qshala,EduTech,Online Curiosity Platform for Kids,Bangalore,Rainmatter Capital,Angel,"370,000"
3,02/09/2020,Winzo,Online Gaming,Online Gaming,New Delhi,"Kalaari Capital Partners, IndigoEdge Managemen...",Series B,"15,500,000"
4,09/09/2020,Hippo Video,Video Customer Experience(CX) Platform,Video Customer Experience(CX) Platform,"Newark, Delaware, United States of Amercia","Alpha Wave Incubation, Exfinity Venture Partne...",Series A,"4,500,000"
5,07/09/2020,Melorra,E-commerce,Online Jewelry Store,Bangalore,"Shadow Holdings, Lightbox.",Debt Financing,"upto 8,900,000"
6,07/09/2020,1mg,E-commerce,Online Pharmacy,Gurgaon,"Gaja Capital, Tata Capital, Partners Group",In Progress,"100,000,000"
7,31/08/2020,mfine,HealthTech,On-Demand Healthcare Services,Bangalore,Caretech Pte Inc,Series B,"5,400,000"
8,31/08/2020,Apna,Human Resources,Recruitment Platform,Bangalore,Lightspeed India and Sequoia Capital India,Series A,"8,000,000"
9,03/09/2020,Railofy,Transportation,WL & RAC protection platform,Mumbai,Chiratae Ventures,Seed,"950,000"

In [101]:
driver.close()

7. Write a program to scrap all the available details of best gaming laptops from digit.in.

In [87]:
from selenium.webdriver.common.keys import Keys

In [101]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get("https://www.digit.in/")

In [102]:
search = driver.find_element_by_xpath("//div[@class='search']")
search.click()

In [103]:
search_btn=driver.find_element_by_id("globalPageSearchText")
search_btn.send_keys("best gaming laptops")

In [104]:
search_btn.send_keys(Keys.ENTER)

In [105]:
driver.find_element_by_id("content_top10").click()

In [106]:
driver.find_element_by_xpath("/html/body/div[6]/div[2]/div[2]/div[4]/a").click()

In [107]:
current_url=driver.current_url
page=requests.get(current_url)   
soup=BeautifulSoup(page.content)

In [108]:
table=soup.find("table",id="summtable")

In [109]:
header=[]
for i in table.find_all("th"):
    header.append(i.text.strip().replace("\n",""))
header
df=pd.DataFrame(columns=header)
df

Empty DataFrame
Columns: [Product Name, Seller, Price]
Index: []

In [110]:
for row in table.find_all("tr")[1:]:
    data=row.find_all("td")
    row_data=[td.text.strip() for td in data]
    length=len(df)
    df.loc[length]=row_data
df

                                    Product Name    Seller      Price
0                    Acer NITRO 5 Ryzen 9 (2021)  Flipkart  ₹ 129,990
1  MSI Stealth 15M 11th Gen Core i7-11375H (2021  Flipkart  ₹ 134,990
2   ASUS ROG Strix Scar 15 Ryzen 9-5900HX (2021)  Flipkart  ₹ 268,990
3                          Alienware Area 51M R2       N/A  ₹ 342,989
4                               Alienware m15 R3    Amazon  ₹ 319,990
5                         ASUS ROG Strix Scar 15  Flipkart  ₹ 215,990
6                          Asus ROG Zephyrus G14    Amazon  ₹ 164,990
7                               Lenovo Legion 5i    Amazon   ₹ 76,988
8                       ASUS ROG ZEPHYRUS DUO 15    Amazon  ₹ 185,000
9                           Acer Aspire 7 gaming    Amazon   ₹ 62,945

In [111]:
specifi=soup.find_all("div",class_="Product-specs")
specifications=[]
for i in specifi:
    for j in soup.find_all("div",class_="Spcs-details"):
        specifications.append(j.text.strip().replace("\n"," "))
specifications

['SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen 9 Octa Core | 2.4 GHz  Memory : 1 TB HDD/16 GBGB DDR4   Weight : 2.4   Dimension : 363.4 x 255 x 23.9   Graphics Processor : NVIDIA GeForce RTX 3070',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : Intel Core i7 11th Gen - 11375H  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.7   Dimension : 358.3 x 248 x 16.15   Graphics Processor : NVIDIA GeForce RTX 3060',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (2560 x 1440)  Processor : AMD Ryzen 9 Octa Core - 5900HX | 3.3 GHz  Memory : 2 TB SSD/32 GBGB DDR4   Weight : 2.30   Dimension : 354 x 259 x 22.6   Graphics Processor : NVIDIA GeForce RTX 3080',
 'SPECIFICATION OS : Windows 10 Home  Display : 17.3" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i7-10700 | 2.90 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 4.1   Dimension : 27.65 x 402.6 x 319.14   Graphics Processor : Intel® UHD Graphics 630   Price : ₹342,989',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (3840 x 2160)  Processor : 10th Gen Intel® Core™ i9-10980HK  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : NA   Dimension : NA   Graphics Processor : NA',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 9 5900HX | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.30   Dimension : 35.4 x 25.9 x 2.26   Graphics Processor : NVIDIA® GeForce RTX™ 3070',
 'SPECIFICATION OS : Windows 10 Home  Display : 14" (1920 x 1080)  Processor : AMD 3rd Gen Ryzen 9 | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.65   Dimension : 32.5 x 22.1 x 1.8   Graphics Processor : NVIDIA GeForce RTX 2060',
 'SPECIFICATION OS : Windows 10 Pro  Display : 15.6" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i5-10300H | 2.50 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.3   Dimension : 363.06 x 259.61 x 23.57   Graphics Processor : NVIDIA® GeForce® GTX 1650 4GB',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (3840 x 1100)  Processor : Intel Core i7 10th Gen 10875H  | NA  Memory : 512 GB SSD/4 GBGB DDR4   Weight : 2.4   Dimension : 268.30 x 360.00 x 20.90   Graphics Processor : NVIDIA GeForce RTX 2070 Max-Q',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 5-5500U hexa-core  | NA  Memory : 512 GB SSD/8 GBGB DDR4   Weight : 2.15   Dimension : 2.29 x 36.3 x 25.4   Graphics Processor : NVIDIA® GeForce® GTX 1650',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen 9 Octa Core | 2.4 GHz  Memory : 1 TB HDD/16 GBGB DDR4   Weight : 2.4   Dimension : 363.4 x 255 x 23.9   Graphics Processor : NVIDIA GeForce RTX 3070',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : Intel Core i7 11th Gen - 11375H  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.7   Dimension : 358.3 x 248 x 16.15   Graphics Processor : NVIDIA GeForce RTX 3060',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (2560 x 1440)  Processor : AMD Ryzen 9 Octa Core - 5900HX | 3.3 GHz  Memory : 2 TB SSD/32 GBGB DDR4   Weight : 2.30   Dimension : 354 x 259 x 22.6   Graphics Processor : NVIDIA GeForce RTX 3080',
 'SPECIFICATION OS : Windows 10 Home  Display : 17.3" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i7-10700 | 2.90 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 4.1   Dimension : 27.65 x 402.6 x 319.14   Graphics Processor : Intel® UHD Graphics 630   Price : ₹342,989',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (3840 x 2160)  Processor : 10th Gen Intel® Core™ i9-10980HK  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : NA   Dimension : NA   Graphics Processor : NA',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 9 5900HX | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.30   Dimension : 35.4 x 25.9 x 2.26   Graphics Processor : NVIDIA® GeForce RTX™ 3070',
 'SPECIFICATION OS : Windows 10 Home  Display : 14" (1920 x 1080)  Processor : AMD 3rd Gen Ryzen 9 | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.65   Dimension : 32.5 x 22.1 x 1.8   Graphics Processor : NVIDIA GeForce RTX 2060',
 'SPECIFICATION OS : Windows 10 Pro  Display : 15.6" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i5-10300H | 2.50 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.3   Dimension : 363.06 x 259.61 x 23.57   Graphics Processor : NVIDIA® GeForce® GTX 1650 4GB',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (3840 x 1100)  Processor : Intel Core i7 10th Gen 10875H  | NA  Memory : 512 GB SSD/4 GBGB DDR4   Weight : 2.4   Dimension : 268.30 x 360.00 x 20.90   Graphics Processor : NVIDIA GeForce RTX 2070 Max-Q',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 5-5500U hexa-core  | NA  Memory : 512 GB SSD/8 GBGB DDR4   Weight : 2.15   Dimension : 2.29 x 36.3 x 25.4   Graphics Processor : NVIDIA® GeForce® GTX 1650',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen 9 Octa Core | 2.4 GHz  Memory : 1 TB HDD/16 GBGB DDR4   Weight : 2.4   Dimension : 363.4 x 255 x 23.9   Graphics Processor : NVIDIA GeForce RTX 3070',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : Intel Core i7 11th Gen - 11375H  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.7   Dimension : 358.3 x 248 x 16.15   Graphics Processor : NVIDIA GeForce RTX 3060',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (2560 x 1440)  Processor : AMD Ryzen 9 Octa Core - 5900HX | 3.3 GHz  Memory : 2 TB SSD/32 GBGB DDR4   Weight : 2.30   Dimension : 354 x 259 x 22.6   Graphics Processor : NVIDIA GeForce RTX 3080',
 'SPECIFICATION OS : Windows 10 Home  Display : 17.3" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i7-10700 | 2.90 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 4.1   Dimension : 27.65 x 402.6 x 319.14   Graphics Processor : Intel® UHD Graphics 630   Price : ₹342,989',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (3840 x 2160)  Processor : 10th Gen Intel® Core™ i9-10980HK  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : NA   Dimension : NA   Graphics Processor : NA',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 9 5900HX | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.30   Dimension : 35.4 x 25.9 x 2.26   Graphics Processor : NVIDIA® GeForce RTX™ 3070',
 'SPECIFICATION OS : Windows 10 Home  Display : 14" (1920 x 1080)  Processor : AMD 3rd Gen Ryzen 9 | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.65   Dimension : 32.5 x 22.1 x 1.8   Graphics Processor : NVIDIA GeForce RTX 2060',
 'SPECIFICATION OS : Windows 10 Pro  Display : 15.6" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i5-10300H | 2.50 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.3   Dimension : 363.06 x 259.61 x 23.57   Graphics Processor : NVIDIA® GeForce® GTX 1650 4GB',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (3840 x 1100)  Processor : Intel Core i7 10th Gen 10875H  | NA  Memory : 512 GB SSD/4 GBGB DDR4   Weight : 2.4   Dimension : 268.30 x 360.00 x 20.90   Graphics Processor : NVIDIA GeForce RTX 2070 Max-Q',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 5-5500U hexa-core  | NA  Memory : 512 GB SSD/8 GBGB DDR4   Weight : 2.15   Dimension : 2.29 x 36.3 x 25.4   Graphics Processor : NVIDIA® GeForce® GTX 1650',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen 9 Octa Core | 2.4 GHz  Memory : 1 TB HDD/16 GBGB DDR4   Weight : 2.4   Dimension : 363.4 x 255 x 23.9   Graphics Processor : NVIDIA GeForce RTX 3070',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : Intel Core i7 11th Gen - 11375H  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.7   Dimension : 358.3 x 248 x 16.15   Graphics Processor : NVIDIA GeForce RTX 3060',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (2560 x 1440)  Processor : AMD Ryzen 9 Octa Core - 5900HX | 3.3 GHz  Memory : 2 TB SSD/32 GBGB DDR4   Weight : 2.30   Dimension : 354 x 259 x 22.6   Graphics Processor : NVIDIA GeForce RTX 3080',
 'SPECIFICATION OS : Windows 10 Home  Display : 17.3" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i7-10700 | 2.90 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 4.1   Dimension : 27.65 x 402.6 x 319.14   Graphics Processor : Intel® UHD Graphics 630   Price : ₹342,989',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (3840 x 2160)  Processor : 10th Gen Intel® Core™ i9-10980HK  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : NA   Dimension : NA   Graphics Processor : NA',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 9 5900HX | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.30   Dimension : 35.4 x 25.9 x 2.26   Graphics Processor : NVIDIA® GeForce RTX™ 3070',
 'SPECIFICATION OS : Windows 10 Home  Display : 14" (1920 x 1080)  Processor : AMD 3rd Gen Ryzen 9 | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.65   Dimension : 32.5 x 22.1 x 1.8   Graphics Processor : NVIDIA GeForce RTX 2060',
 'SPECIFICATION OS : Windows 10 Pro  Display : 15.6" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i5-10300H | 2.50 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.3   Dimension : 363.06 x 259.61 x 23.57   Graphics Processor : NVIDIA® GeForce® GTX 1650 4GB',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (3840 x 1100)  Processor : Intel Core i7 10th Gen 10875H  | NA  Memory : 512 GB SSD/4 GBGB DDR4   Weight : 2.4   Dimension : 268.30 x 360.00 x 20.90   Graphics Processor : NVIDIA GeForce RTX 2070 Max-Q',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 5-5500U hexa-core  | NA  Memory : 512 GB SSD/8 GBGB DDR4   Weight : 2.15   Dimension : 2.29 x 36.3 x 25.4   Graphics Processor : NVIDIA® GeForce® GTX 1650',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen 9 Octa Core | 2.4 GHz  Memory : 1 TB HDD/16 GBGB DDR4   Weight : 2.4   Dimension : 363.4 x 255 x 23.9   Graphics Processor : NVIDIA GeForce RTX 3070',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : Intel Core i7 11th Gen - 11375H  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.7   Dimension : 358.3 x 248 x 16.15   Graphics Processor : NVIDIA GeForce RTX 3060',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (2560 x 1440)  Processor : AMD Ryzen 9 Octa Core - 5900HX | 3.3 GHz  Memory : 2 TB SSD/32 GBGB DDR4   Weight : 2.30   Dimension : 354 x 259 x 22.6   Graphics Processor : NVIDIA GeForce RTX 3080',
 'SPECIFICATION OS : Windows 10 Home  Display : 17.3" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i7-10700 | 2.90 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 4.1   Dimension : 27.65 x 402.6 x 319.14   Graphics Processor : Intel® UHD Graphics 630   Price : ₹342,989',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (3840 x 2160)  Processor : 10th Gen Intel® Core™ i9-10980HK  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : NA   Dimension : NA   Graphics Processor : NA',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 9 5900HX | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.30   Dimension : 35.4 x 25.9 x 2.26   Graphics Processor : NVIDIA® GeForce RTX™ 3070',
 'SPECIFICATION OS : Windows 10 Home  Display : 14" (1920 x 1080)  Processor : AMD 3rd Gen Ryzen 9 | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.65   Dimension : 32.5 x 22.1 x 1.8   Graphics Processor : NVIDIA GeForce RTX 2060',
 'SPECIFICATION OS : Windows 10 Pro  Display : 15.6" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i5-10300H | 2.50 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.3   Dimension : 363.06 x 259.61 x 23.57   Graphics Processor : NVIDIA® GeForce® GTX 1650 4GB',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (3840 x 1100)  Processor : Intel Core i7 10th Gen 10875H  | NA  Memory : 512 GB SSD/4 GBGB DDR4   Weight : 2.4   Dimension : 268.30 x 360.00 x 20.90   Graphics Processor : NVIDIA GeForce RTX 2070 Max-Q',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 5-5500U hexa-core  | NA  Memory : 512 GB SSD/8 GBGB DDR4   Weight : 2.15   Dimension : 2.29 x 36.3 x 25.4   Graphics Processor : NVIDIA® GeForce® GTX 1650',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen 9 Octa Core | 2.4 GHz  Memory : 1 TB HDD/16 GBGB DDR4   Weight : 2.4   Dimension : 363.4 x 255 x 23.9   Graphics Processor : NVIDIA GeForce RTX 3070',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : Intel Core i7 11th Gen - 11375H  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.7   Dimension : 358.3 x 248 x 16.15   Graphics Processor : NVIDIA GeForce RTX 3060',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (2560 x 1440)  Processor : AMD Ryzen 9 Octa Core - 5900HX | 3.3 GHz  Memory : 2 TB SSD/32 GBGB DDR4   Weight : 2.30   Dimension : 354 x 259 x 22.6   Graphics Processor : NVIDIA GeForce RTX 3080',
 'SPECIFICATION OS : Windows 10 Home  Display : 17.3" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i7-10700 | 2.90 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 4.1   Dimension : 27.65 x 402.6 x 319.14   Graphics Processor : Intel® UHD Graphics 630   Price : ₹342,989',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (3840 x 2160)  Processor : 10th Gen Intel® Core™ i9-10980HK  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : NA   Dimension : NA   Graphics Processor : NA',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 9 5900HX | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.30   Dimension : 35.4 x 25.9 x 2.26   Graphics Processor : NVIDIA® GeForce RTX™ 3070',
 'SPECIFICATION OS : Windows 10 Home  Display : 14" (1920 x 1080)  Processor : AMD 3rd Gen Ryzen 9 | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.65   Dimension : 32.5 x 22.1 x 1.8   Graphics Processor : NVIDIA GeForce RTX 2060',
 'SPECIFICATION OS : Windows 10 Pro  Display : 15.6" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i5-10300H | 2.50 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.3   Dimension : 363.06 x 259.61 x 23.57   Graphics Processor : NVIDIA® GeForce® GTX 1650 4GB',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (3840 x 1100)  Processor : Intel Core i7 10th Gen 10875H  | NA  Memory : 512 GB SSD/4 GBGB DDR4   Weight : 2.4   Dimension : 268.30 x 360.00 x 20.90   Graphics Processor : NVIDIA GeForce RTX 2070 Max-Q',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 5-5500U hexa-core  | NA  Memory : 512 GB SSD/8 GBGB DDR4   Weight : 2.15   Dimension : 2.29 x 36.3 x 25.4   Graphics Processor : NVIDIA® GeForce® GTX 1650',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen 9 Octa Core | 2.4 GHz  Memory : 1 TB HDD/16 GBGB DDR4   Weight : 2.4   Dimension : 363.4 x 255 x 23.9   Graphics Processor : NVIDIA GeForce RTX 3070',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : Intel Core i7 11th Gen - 11375H  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.7   Dimension : 358.3 x 248 x 16.15   Graphics Processor : NVIDIA GeForce RTX 3060',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (2560 x 1440)  Processor : AMD Ryzen 9 Octa Core - 5900HX | 3.3 GHz  Memory : 2 TB SSD/32 GBGB DDR4   Weight : 2.30   Dimension : 354 x 259 x 22.6   Graphics Processor : NVIDIA GeForce RTX 3080',
 'SPECIFICATION OS : Windows 10 Home  Display : 17.3" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i7-10700 | 2.90 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 4.1   Dimension : 27.65 x 402.6 x 319.14   Graphics Processor : Intel® UHD Graphics 630   Price : ₹342,989',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (3840 x 2160)  Processor : 10th Gen Intel® Core™ i9-10980HK  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : NA   Dimension : NA   Graphics Processor : NA',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 9 5900HX | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.30   Dimension : 35.4 x 25.9 x 2.26   Graphics Processor : NVIDIA® GeForce RTX™ 3070',
 'SPECIFICATION OS : Windows 10 Home  Display : 14" (1920 x 1080)  Processor : AMD 3rd Gen Ryzen 9 | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.65   Dimension : 32.5 x 22.1 x 1.8   Graphics Processor : NVIDIA GeForce RTX 2060',
 'SPECIFICATION OS : Windows 10 Pro  Display : 15.6" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i5-10300H | 2.50 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.3   Dimension : 363.06 x 259.61 x 23.57   Graphics Processor : NVIDIA® GeForce® GTX 1650 4GB',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (3840 x 1100)  Processor : Intel Core i7 10th Gen 10875H  | NA  Memory : 512 GB SSD/4 GBGB DDR4   Weight : 2.4   Dimension : 268.30 x 360.00 x 20.90   Graphics Processor : NVIDIA GeForce RTX 2070 Max-Q',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 5-5500U hexa-core  | NA  Memory : 512 GB SSD/8 GBGB DDR4   Weight : 2.15   Dimension : 2.29 x 36.3 x 25.4   Graphics Processor : NVIDIA® GeForce® GTX 1650',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen 9 Octa Core | 2.4 GHz  Memory : 1 TB HDD/16 GBGB DDR4   Weight : 2.4   Dimension : 363.4 x 255 x 23.9   Graphics Processor : NVIDIA GeForce RTX 3070',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : Intel Core i7 11th Gen - 11375H  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.7   Dimension : 358.3 x 248 x 16.15   Graphics Processor : NVIDIA GeForce RTX 3060',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (2560 x 1440)  Processor : AMD Ryzen 9 Octa Core - 5900HX | 3.3 GHz  Memory : 2 TB SSD/32 GBGB DDR4   Weight : 2.30   Dimension : 354 x 259 x 22.6   Graphics Processor : NVIDIA GeForce RTX 3080',
 'SPECIFICATION OS : Windows 10 Home  Display : 17.3" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i7-10700 | 2.90 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 4.1   Dimension : 27.65 x 402.6 x 319.14   Graphics Processor : Intel® UHD Graphics 630   Price : ₹342,989',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (3840 x 2160)  Processor : 10th Gen Intel® Core™ i9-10980HK  | NA  Memory : 1 TB SSD/16 GBGB DDR4   Weight : NA   Dimension : NA   Graphics Processor : NA',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 9 5900HX | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.30   Dimension : 35.4 x 25.9 x 2.26   Graphics Processor : NVIDIA® GeForce RTX™ 3070',
 'SPECIFICATION OS : Windows 10 Home  Display : 14" (1920 x 1080)  Processor : AMD 3rd Gen Ryzen 9 | 3.3 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 1.65   Dimension : 32.5 x 22.1 x 1.8   Graphics Processor : NVIDIA GeForce RTX 2060',
 'SPECIFICATION OS : Windows 10 Pro  Display : 15.6" (1920 x 1080)  Processor : 10th Gen Intel® Core™ i5-10300H | 2.50 GHz  Memory : 1 TB SSD/16 GBGB DDR4   Weight : 2.3   Dimension : 363.06 x 259.61 x 23.57   Graphics Processor : NVIDIA® GeForce® GTX 1650 4GB',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (3840 x 1100)  Processor : Intel Core i7 10th Gen 10875H  | NA  Memory : 512 GB SSD/4 GBGB DDR4   Weight : 2.4   Dimension : 268.30 x 360.00 x 20.90   Graphics Processor : NVIDIA GeForce RTX 2070 Max-Q',
 'SPECIFICATION OS : Windows 10 Home  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen™ 5-5500U hexa-core  | NA  Memory : 512 GB SSD/8 GBGB DDR4   Weight : 2.15   Dimension : 2.29 x 36.3 x 25.4   Graphics Processor : NVIDIA® GeForce® GTX 1650',
 'SPECIFICATION OS : Windows 10  Display : 15.6" (1920 x 1080)  Processor : AMD Ryzen 9 Octa Core | 2.4 GHz  Memory : 1 TB HDD/16 GBGB DDR4   Weight : 2.4   Dimension : 363.4 x 255 x 23.9   Graphics Processor : NVIDIA GeForce RTX 3070',

In [112]:
df["specifications"]=specifications[10]
df

,Product Name,Seller,Price,specifications
0,Acer NITRO 5 Ryzen 9 (2021),Flipkart,"₹ 129,990","SPECIFICATION OS : Windows 10 Display : 15.6""..."
1,MSI Stealth 15M 11th Gen Core i7-11375H (2021,Flipkart,"₹ 134,990","SPECIFICATION OS : Windows 10 Display : 15.6""..."
2,ASUS ROG Strix Scar 15 Ryzen 9-5900HX (2021),Flipkart,"₹ 268,990","SPECIFICATION OS : Windows 10 Display : 15.6""..."
3,Alienware Area 51M R2,N/A,"₹ 342,989","SPECIFICATION OS : Windows 10 Display : 15.6""..."
4,Alienware m15 R3,Amazon,"₹ 319,990","SPECIFICATION OS : Windows 10 Display : 15.6""..."
5,ASUS ROG Strix Scar 15,Flipkart,"₹ 215,990","SPECIFICATION OS : Windows 10 Display : 15.6""..."
6,Asus ROG Zephyrus G14,Amazon,"₹ 164,990","SPECIFICATION OS : Windows 10 Display : 15.6""..."
7,Lenovo Legion 5i,Amazon,"₹ 76,988","SPECIFICATION OS : Windows 10 Display : 15.6""..."
8,ASUS ROG ZEPHYRUS DUO 15,Amazon,"₹ 185,000","SPECIFICATION OS : Windows 10 Display : 15.6""..."
9,Acer Aspire 7 gaming,Amazon,"₹ 62,945","SPECIFICATION OS : Windows 10 Display : 15.6""..."

In [113]:
driver.close()

8. Write a python program to scrape the details for all billionaires from www.forbes.com.
Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”,
“Industry”.

In [84]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get("https://www.forbes.com/billionaires/")

In [87]:
Rank=[]
Person_Name=[]
total_net_worth=[]
Age=[]
country_of_citizenship=[]
Source=[]
industry=[]

while(True):
    
    rank= driver.find_elements_by_xpath("//div[@class='rank']")
    for i in rank:
        Rank.append(i.text)
    time.sleep(1)
    
    name= driver.find_elements_by_xpath("//div[@class='personName']//div")
    for i in name:
        Person_Name.append(i.text)
    time.sleep(1)
    
    net= driver.find_elements_by_xpath("//div[@class='netWorth']")
    for i in net:
        total_net_worth.append(i.text)
    time.sleep(1)
    
    ages= driver.find_elements_by_xpath("//div[@class='age']")
    for i in ages:
        Age.append(i.text)
    time.sleep(1)
    
    country= driver.find_elements_by_xpath("//div[@class='countryOfCitizenship']")
    for i in country:
        country_of_citizenship.append(i.text)
    time.sleep(1)
    
    source= driver.find_elements_by_xpath("//div[@class='source']")
    for i in source:
        Source.append(i.text)
    time.sleep(1)
    
    indus= driver.find_elements_by_xpath("//div[@class='category']")
    for i in indus:
        industry.append(i.text)
    time.sleep(1)
    
     
    try:
        next_button = driver.find_element_by_xpath("//button[@class='pagination-btn pagination-btn--next ']")
        next_button.click()
    except:
        break

In [89]:
df=pd.DataFrame()
df["RANK"]=Rank
df["NAME"]=Person_Name
df["NET_WORTH"]=total_net_worth
df["AGE"]=Age
df["COUNTRY_OF_CITIZENSHIP"]=country_of_citizenship
df["SOURCE"]=Source
df["INDUSTRY"]=industry

In [90]:
df

,RANK,NAME,NET_WORTH,AGE,COUNTRY_OF_CITIZENSHIP,SOURCE,INDUSTRY
0,1.,Jeff Bezos,$177 B,57,United States,Amazon,Technology
1,2.,Elon Musk,$151 B,49,United States,"Tesla, SpaceX",Automotive
2,3.,Bernard Arnault & family,$150 B,72,France,LVMH,Fashion & Retail
3,4.,Bill Gates,$124 B,65,United States,Microsoft,Technology
4,5.,Mark Zuckerberg,$97 B,36,United States,Facebook,Technology
...,...,...,...,...,...,...,...
2750,2674.,Daniel Yong Zhang,$1 B,49,China,e-commerce,Technology
2751,2674.,Zhang Yuqiang,$1 B,65,China,Fiberglass,Manufacturing
2752,2674.,Zhao Meiguang,$1 B,58,China,gold mining,Metals & Mining
2753,2674.,Zhong Naixiong,$1 B,58,China,conglomerate,Diversified
2754,2674.,Zhou Wei family,$1 B,54,China,Software,Technology

In [91]:
driver.close()

9. Write a program to extract at least 500 Comments, Comment upvote and time when comment
was posted from any YouTube Video.

In [140]:
!pip install youtube_comment_scraper_python

Collecting youtube_comment_scraper_python
  Downloading youtube-comment-scraper-python-1.0.0.tar.gz (2.6 kB)
Requirement already satisfied: requests in c:\users\sanjay\anaconda3\lib\site-packages (from youtube_comment_scraper_python) (2.24.0)
Collecting bot-studio
  Downloading bot_studio-1.2.2.tar.gz (65.7 MB)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\sanjay\anaconda3\lib\site-packages (from requests->youtube_comment_scraper_python) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sanjay\anaconda3\lib\site-packages (from requests->youtube_comment_scraper_python) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\users\sanjay\anaconda3\lib\site-packages (from requests->youtube_comment_scraper_python) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\sanjay\anaconda3\lib\site-packages (from requests->youtube_comment_scraper_python) (3.0.4)
Requirement already satisfied: tqdm in c:\users\sanjay\anaconda3\lib\site-packages (from bot-studio->youtube_comment_scraper_python) (4.50.2)
Building wheels for collected packages: youtube-comment-scraper-python, bot-studio
  Building wheel for youtube-comment-scraper-python (setup.py): started
  Building wheel for youtube-comment-scraper-python (setup.py): finished with status 'done'
  Created wheel for youtube-comment-scraper-python: filename=youtube_comment_scraper_python-1.0.0-py3-none-any.whl size=2503 sha256=5344335addf4ddac868a220f3a22651f60f7ddf17bb819bf0a5688c7e4923dfd
  Stored in directory: c:\users\sanjay\appdata\local\pip\cache\wheels\f8\c2\07\62c6de3fa077a37e888eeec058dd6a057eeaec518fd2d740f4
  Building wheel for bot-studio (setup.py): started
  Building wheel for bot-studio (setup.py): finished with status 'done'
  Created wheel for bot-studio: filename=bot_studio-1.2.2-py3-none-any.whl size=65730230 sha256=03e4cc712353c4be29311e77baed6e9d0ae8f8dffe3c3fa4758e64e1477bcefb
  Stored in directory: c:\users\sanjay\appdata\local\pip\cache\wheels\c4\63\8e\0d2c1bca327617282ddf2855fedbaf561a95b9e78c37824776
Successfully built youtube-comment-scraper-python bot-studio
Installing collected packages: bot-studio, youtube-comment-scraper-python
Successfully installed bot-studio-1.2.2 youtube-comment-scraper-python-1.0.0

In [3]:
from youtube_comment_scraper_python import *
youtube.open("https://www.youtube.com/watch?v=HkjaFXNEcvE&list=RDHkjaFXNEcvE&start_radio=1")
for i in range(0,27):
    time.sleep(10)
    response=youtube.video_comments()
    data=response['body']

Progress: 100%|██████████| 200.0/200 [00:24<00:00,  8.19it/s]
Progress: 100%|██████████| 200.0/200 [00:32<00:00,  6.12it/s]
Progress: 100%|██████████| 200.0/200 [00:42<00:00,  4.68it/s]
Progress: 100%|██████████| 200.0/200 [00:56<00:00,  3.51it/s]
Progress: 100%|██████████| 200.0/200 [01:11<00:00,  2.81it/s]
Progress: 100%|██████████| 200.0/200 [01:23<00:00,  2.40it/s]
Progress: 100%|██████████| 200.0/200 [01:37<00:00,  2.04it/s]
Progress: 100%|██████████| 200.0/200 [01:54<00:00,  1.75it/s]
Progress: 100%|██████████| 200.0/200 [01:56<00:00,  1.72it/s]
Progress: 100%|██████████| 200.0/200 [02:12<00:00,  1.51it/s]
Progress: 100%|██████████| 200.0/200 [02:32<00:00,  1.31it/s]
Progress: 100%|██████████| 200.0/200 [02:47<00:00,  1.20it/s]
Progress: 100%|██████████| 200.0/200 [03:07<00:00,  1.07it/s]
Progress: 100%|██████████| 200.0/200 [03:40<00:00,  1.10s/it]
Progress: 100%|██████████| 200.0/200 [03:44<00:00,  1.12s/it]
Progress: 100%|██████████| 200.0/200 [04:04<00:00,  1.22s/it]
Progress: 100%|██████████| 200.0/200 [04:33<00:00,  1.37s/it]
Progress: 100%|██████████| 200.0/200 [04:51<00:00,  1.46s/it]
Progress: 100%|██████████| 200.0/200 [05:14<00:00,  1.57s/it]
Progress: 100%|██████████| 200.0/200 [05:26<00:00,  1.63s/it]
Progress: 100%|██████████| 200.0/200 [06:00<00:00,  1.80s/it]
Progress: 100%|██████████| 200.0/200 [06:27<00:00,  1.94s/it]
Progress: 100%|██████████| 200.0/200 [07:00<00:00,  2.10s/it]
Progress: 100%|██████████| 200.0/200 [07:30<00:00,  2.25s/it]
Progress: 100%|██████████| 200.0/200 [07:53<00:00,  2.37s/it]
Progress: 100%|██████████| 200.0/200 [08:19<00:00,  2.50s/it]
Progress: 100%|██████████| 200.0/200 [09:15<00:00,  2.78s/it]

In [5]:
df=pd.DataFrame(data)
df

,Comment,Likes,Time,UserLink,user
0,Berlin is a legend. I'm watching season 3 and ...,3.1K,1 year ago (edited),/channel/UCsV515HYJNWFvTORWJxI1rg,MadrasaTech Official
1,Denver's laugh is my phone ringtone.,2.2K,10 months ago,/channel/UCRK-QBVhk1Lvph5CkGXEeDQ,Santosh SP
2,Love like Tokyo\nThink like Professor\nAct lik...,2.2K,10 months ago (edited),/channel/UCvBxOB9h42P-3CTdEOZKvJg,Cham
3,Love like Tokyo\nHack like Rio \nFriendship li...,394,5 months ago (edited),/channel/UC1cDX2B3OwVllUoY6hK7_Gw,Yasodha VVCRM
4,Kids cried when Nairobi died. \nMen cried when...,1.9K,9 months ago,/channel/UCmolH2zh_BfTD9UiYpSlMZg,Siddhant Kamat
...,...,...,...,...,...
515,Professor nailed it..,5,1 year ago,/channel/UCr_9bpeOO0HFQ2eWpRMutXA,Sagar Kumar
516,Waiting for The Season Finale,1,5 months ago,/channel/UCaK5DPI6n3sJbtPvjuN4zlg,Sarlong Bey
517,who always liked arturo roman ! I know everyon...,2,8 months ago,/channel/UCa5ep3j8Q0CBn5qqEztryXg,Kushagra
518,Kids cried when Nairobi died. \r\nMen cried wh...,0,3 months ago,/channel/UCqj08iAQwbK76aWHyRqbC-Q,Ponnusamy Thillaiarasu
519,Please Wash My Brain I Wanna See This Series A...,0,6 months ago,/channel/UC9_5IQOy9BkHCzyXV1I1Qnw,Moneyheist_comic

10. Write a python program to scrape a data for all available Hostels from
cin “London” location. You have to scrape hostel name,
distance from city centre, ratings, total reviews, overall reviews, privates from price, dorms
from price, facilities and property description.

In [52]:
driver=webdriver.Chrome("chromedriver.exe")
driver.get("https://www.hostelworld.com/s?q=London,%20England&country=England&city=London&type=city&id=3&from=2021-10-25&to=2021-10-28&guests=2&page=1")

In [53]:
page_url=[]
data = []  
page_count = 1
columns = ["hostel name","distance from city centre"]

for i in range(3):
    time.sleep(3)
    hostels = driver.find_elements(By.XPATH,"//div[@class='property']//div[@class='title-row']")
    print(f"hostels in page {page_count}: ",len(hostels))
    
    for hostel in hostels:
        
        try:
            h_name=hostel.find_element(By.XPATH,".//h2[@class='title title-6']").text
            data_row = hostel.text.split("\n")
        except:
            h_name="-"
        time.sleep(2)
        
        try:
            distance=hostel.find_element(By.XPATH,".//div[@class='subtitle body-3']").text
        except:
            distance="-"
        time.sleep(2)
        
        try:
            url=hostel.find_element(By.XPATH,".//h2[@class='title title-6']/a").get_attribute('href')
        except:
            url="-"
        
        data.append([h_name,distance])
        page_url.append(url)
    page_count += 1
    try:
        driver.find_element_by_xpath("//div[@class='pagination-item pagination-next']").click()
        time.sleep(2)
    except:
        driver.find_element_by_xpath("//div[@class='pagination-item pagination-first']").click()
        time.sleep(2)
        
print("Done Scraping!!!")

hostels in page 1:  32
hostels in page 2:  30
hostels in page 3:  12
Done Scraping!!!

In [54]:
df=pd.DataFrame(data,columns=columns)

In [55]:
df

,hostel name,distance from city centre
0,-,Hostel - 5.5km from city centre
1,-,Hostel - 11.9km from city centre
2,St Christopher's Inn - Liverpool Street,Hostel - 3.2km from city centre Show on Map
3,Astor Hyde Park,Hostel - 4.3km from city centre Show on Map
4,St Christopher's Village,Hostel - 1.8km from city centre Show on Map
...,...,...
69,Barry House,Bed and Breakfast - 4.2km from city centre Sho...
70,Park Hotel Essex,Hotel - 24.1km from city centre Show on Map
71,Cranbrook Hotel,Hotel - 14.8km from city centre Show on Map
72,Aron Guest House,Bed and Breakfast - 13.1km from city centre Sh...
73,MacDonald Hotel,Hotel - 3.3km from city centre Show on Map

In [56]:
df=df.drop([0,1])

In [57]:
df

,hostel name,distance from city centre
2,St Christopher's Inn - Liverpool Street,Hostel - 3.2km from city centre Show on Map
3,Astor Hyde Park,Hostel - 4.3km from city centre Show on Map
4,St Christopher's Village,Hostel - 1.8km from city centre Show on Map
5,Smart Camden Inn Hostel,Hostel - 4.4km from city centre Show on Map
6,The Finnish Church in London,Hostel - 4.5km from city centre Show on Map
...,...,...
69,Barry House,Bed and Breakfast - 4.2km from city centre Sho...
70,Park Hotel Essex,Hotel - 24.1km from city centre Show on Map
71,Cranbrook Hotel,Hotel - 14.8km from city centre Show on Map
72,Aron Guest House,Bed and Breakfast - 13.1km from city centre Sh...
73,MacDonald Hotel,Hotel - 3.3km from city centre Show on Map

In [58]:
page_url=page_url[2:]
len(page_url)

72

In [59]:
rating=[]
f=[]
d=[]

for i in page_url:
    driver.get(i)
    time.sleep(3)
    
    try:
        ratings = driver.find_element_by_xpath("//div[@class='rating rating-summary-container big clickable']")
        rating.append(ratings.text)
    except:
        ratings="-"
        rating.append(ratings)
    
    try:
        fs = driver.find_element_by_xpath("//div[@class='facilities-container']")
        f.append(fs.text)
    except:
        fs="-"
        f.append(fs)
    
    try:  
        ds= driver.find_element_by_xpath("//div[@class='description-container']")
        d.append(ds.text)
    except:
        ds="-"
        d.append(ds)

In [60]:
df["ratings"]=rating
df["facilities"]=f
df["property description"]=d
df

,hostel name,distance from city centre,ratings,facilities,property description
2,St Christopher's Inn - Liverpool Street,Hostel - 3.2km from city centre Show on Map,9.3\nSuperb\n362 Total Reviews,Facilities\nFree\nLinen Included Free City Map...,Property Description\nCOVID 19 Policy Update.\...
3,Astor Hyde Park,Hostel - 4.3km from city centre Show on Map,8.9\nFabulous\n11355 Total Reviews,Facilities\nFree\nLinen Included Free City Map...,Hostelworld says\nNote: 18-40 yrs old only. As...
4,St Christopher's Village,Hostel - 1.8km from city centre Show on Map,8.3\nFabulous\n10886 Total Reviews,Facilities\nFree\nLinen Included Free City Map...,Hostelworld says\nHostelworld visitors have sa...
5,Smart Camden Inn Hostel,Hostel - 4.4km from city centre Show on Map,9.0\nSuperb\n2699 Total Reviews,Facilities\nFree\nLinen Included Free City Map...,Property Description\nLocated in the middle of...
6,The Finnish Church in London,Hostel - 4.5km from city centre Show on Map,9.5\nSuperb\n194 Total Reviews,Facilities\nFree\nLinen Included Free City Map...,Property Description\nAt the The Finnish Churc...
...,...,...,...,...,...
69,Barry House,Bed and Breakfast - 4.2km from city centre Sho...,9.0\nSuperb\n4 Total Reviews,Facilities\nFree\nFree Breakfast Free City Map...,Property Description\nBarry House is a Central...
70,Park Hotel Essex,Hotel - 24.1km from city centre Show on Map,No Rating\n0 Total Reviews,Facilities\nFree\nFree Breakfast Free Parking\...,Property Description\nThis Hotel is the right ...
71,Cranbrook Hotel,Hotel - 14.8km from city centre Show on Map,No Rating\n0 Total Reviews,Facilities\nFree\nFree Breakfast Free Parking\...,Property Description\nWe are located about twe...
72,Aron Guest House,Bed and Breakfast - 13.1km from city centre Sh...,No Rating\n0 Total Reviews,Facilities\nFree\nFree Parking Towels Included...,Property Description\nAron Guest House provide...
73,MacDonald Hotel,Hotel - 3.3km from city centre Show on Map,9.2\nSuperb\n248 Total Reviews,Facilities\nFree\nFree Breakfast Linen Include...,Property Description\nMost of our visitors fir...

In [61]:
driver.close()